pipeline {
    agent any

    environment {
        IMAGE_NAME = "silvy08/banking-app:latest"
        APP_SERVER_IP = "172.31.3.32"
        REMOTE_USER = "ubuntu"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Silver-08/star-agile-banking-finance.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                sh """
                docker build -t $IMAGE_NAME .
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                docker push $IMAGE_NAME
                """
            }
        }

        stage('Deploy to App Server') {
            steps {
                sshagent (credentials: ['your-ssh-key-id']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no $REMOTE_USER@$APP_SERVER_IP <<EOF
                      docker pull $IMAGE_NAME
                      docker stop banking-app || true
                      docker rm banking-app || true
                      docker run -d --name banking-app -p 8080:8080 $IMAGE_NAME
                    EOF
                    """
                }
            }
        }

        stage('Test Deployment') {
            steps {
                sh 'curl -s http://18.144.171.191:8080 || echo "App not reachable"'
            }
        }
    }
}
